// LB-B35 CP1 — generates the results tables (markdown) from grid.json files. No interpretation here.
// Usage: node report.mjs <gridOrig> <gridFloor> <gridUncapped>
import { readFileSync } from 'node:fs';
const load = (p) => JSON.parse(readFileSync(p, 'utf8'));
const G = { orig: load(process.argv[2]), floor: load(process.argv[3]), unc: load(process.argv[4]) };
const mean = (a) => {
  const b = a.filter(Number.isFinite);
  return b.length ? b.reduce((x, y) => x + y, 0) / b.length : NaN;
};
const f = (v, d = 3) => (Number.isFinite(v) ? v.toFixed(d) : 'n/a');
const pct = (v) => (Number.isFinite(v) ? (100 * v).toFixed(1) + '%' : 'n/a');
const SHOW = [
  'V1',
  'LAD-R/G3-365',
  'LAD-B/G3-365',
  'ENG-CLAMP/G3-365',
  'ENG-CLAMP/G3-180',
  'ENG-CLAMP/F21',
  'LAD-R/F21',
  'ENG-LATE/G3-365',
  'ENG-LAPSE/G3-365',
];
const cellsOf = (grid, id, pred) => grid.results.find((r) => r.cand === id).cells.filter(pred);
const agg = (cells, key) => mean(cells.map((c) => mean(c[key])));
const lines = [];
const out = (s = '') => lines.push(s);

function checkpointTable(variant, att, N) {
  out(
    `#### ${variant}: N=${N}, attendance ${att}, mean over the 12 decay learner models, 100 seeds each`,
  );
  out(
    '| candidate | K30 | K90 | K180 | K365 | reviews by d90 | d365 | recovery-mode share d365 | p95 overdue d365 (days) | Box4+ d365 | Box5 d365 |',
  );
  out('|---|---|---|---|---|---|---|---|---|---|---|');
  for (const id of SHOW) {
    const c = cellsOf(G[variant], id, (x) => x.kind === 'decay' && x.att === att && x.N === N);
    if (!c.length) continue;
    out(
      `| ${id} | ${f(agg(c, 'K30'))} | ${f(agg(c, 'K90'))} | ${f(agg(c, 'K180'))} | ${f(agg(c, 'K365'))} | ${f(agg(c, 'reviews90'), 0)} | ${f(agg(c, 'reviews365'), 0)} | ${pct(agg(c, 'rec365'))} | ${f(agg(c, 'p95_365'), 1)} | ${pct(agg(c, 'b4p365'))} | ${pct(agg(c, 'b5p365'))} |`,
    );
  }
  out();
}
function recallTable(variant, att) {
  out(
    `#### ${variant}: constant recall probability, N=35, attendance ${att}, day 365 (box shares of all cards)`,
  );
  out(
    '| candidate | p | Box4+ | Box5 | recovery-mode share | reviews by d365 | due at d365 | introduced by d30 |',
  );
  out('|---|---|---|---|---|---|---|---|');
  for (const id of ['V1', 'LAD-R/G3-365', 'ENG-CLAMP/G3-365', 'ENG-LAPSE/G3-365'])
    for (const p of [0.5, 0.65, 0.75, 0.85, 0.95]) {
      const c = cellsOf(
        G[variant],
        id,
        (x) => x.kind === 'const' && x.att === att && x.model === `p${p}`,
      );
      out(
        `| ${id} | ${p} | ${pct(agg(c, 'b4p365'))} | ${pct(agg(c, 'b5p365'))} | ${pct(agg(c, 'rec365'))} | ${f(agg(c, 'reviews365'), 0)} | ${f(agg(c, 'dueNow365'), 1)} | ${f(agg(c, 'intro30'), 1)} |`,
      );
    }
  out();
}
function newCardTable(variant) {
  out(
    `#### ${variant}: new-card interaction (curriculum of 300 cards, attendance A1, decay models)`,
  );
  out(
    '| candidate | introduced by d30 | d90 | d365 | recovery-mode share d365 | due backlog at d365 |',
  );
  out('|---|---|---|---|---|---|');
  for (const id of ['V1', 'LAD-R/G3-365', 'ENG-CLAMP/G3-365']) {
    const c = cellsOf(G[variant], id, (x) => x.kind === 'decay' && x.att === 'A1' && x.N === 300);
    out(
      `| ${id} | ${f(agg(c, 'intro30'), 1)} | ${f(agg(c, 'intro90'), 1)} | ${f(agg(c, 'intro365'), 1)} | ${pct(agg(c, 'rec365'))} | ${f(agg(c, 'dueNow365'), 0)} |`,
    );
  }
  out();
}
out('# LB-B35 CP1 — generated result tables');
out();
out(
  `Generated by \`tools/learning-sim/report.mjs\` from grid files (seeds: ${G.orig.seeds}). No interpretation in this file.`,
);
out(
  'K = fraction of curriculum the simulated learner would recall today (see pre-registration section 4). `orig` = pre-registered learner model; `floor` = amendment A15 (half-life cannot fall below first exposure); `unc` = amendment A16 (report only: planner cap removed).',
);
out();
for (const v of ['floor', 'orig']) {
  out(`## Day-30/90/180/365 behavior (${v})`);
  out();
  for (const att of ['A1', 'A2', 'A3']) checkpointTable(v, att, 35);
}
checkpointTable('unc', 'A1', 35);
checkpointTable('unc', 'A2', 35);
out('## Behavior at different recall levels');
out();
for (const v of ['floor']) recallTable(v, 'A1');
out('## New-card interaction and recovery pressure');
out();
newCardTable('floor');
newCardTable('orig');
console.log(lines.join('\n'));
